# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorUbuntuJupyter do |servidorUbuntuJupyter|
    servidorUbuntuJupyter.vm.box = "bento/ubuntu-22.04"
    servidorUbuntuJupyter.vm.box_download_insecure = true
    servidorUbuntuJupyter.vm.network :private_network, ip: "192.168.100.4"
    servidorUbuntuJupyter.vm.hostname = "servidorUbuntuJupyter"
    servidorUbuntuJupyter.vm.provision "shell", path: "script.sh"
  end
end

